### ISSUE TITLE
Failed to start Graylog : "removed 0 history items"

### ISSUE THREAD

**Issue by flexbrane** [cvtienhoven/graylog-plugin-aggregates#13]
Hi,

I have graylog server running into a docker container (https://hub.docker.com/r/graylog2/server/). When I put the `.jar` into the `plugin` folder and I restart graylog, I cannot load graylog anymore.

In the console of my web browser, I can see:

```sh
/api/system/cluster/node: Failed to load resource: the server responded with a status of 401 ()
```

Graylog logs gives:

```sh
INFO : org.graylog.plugins.aggregates.maintenance.AggregatesMaintenance - removed 0 history items
```

Finaly, on my reverse proxy:

```sh
"GET /assets/plugin/org.graylog.plugins.aggregates.AggregatesPlugin/plugin.org.graylog.plugins.aggregates.AggregatesPlugin.7bd8ef4d6980339762bb.js HTTP/2.0" 200
"GET /api/system/cluster/node HTTP/2.0" 401
```

Any help regarding my problem? 

Thanks!

**Comment by cvtienhoven** [comment]
The log line "removed 0 history items" is not an error, it's just an indication that no historic hits have to be purged by the plugin. So that seems to work as it should. You're hitting a 401 response on the API from the frontend, which means you're not authorized. How exactly do you restart Graylog? Are you sure that any account information is persisted?

**Comment by flexbrane** [comment]
I tried to delete and create again the graylog2 docker container. All configuration remain, this error happen when I am connected.

Well... I am asking for help, I have restarted (again) graylog, and now this is working!

So, problem solved. Thank you for your help and fast answer. Pretty amazing plugin by the way :-)

**Comment by cvtienhoven** [comment]
Cool! Thanks and have fun with it :)
